[package]
name = "coresight-rs"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
dbg-probe = { path = "../dbg-probe" }
dbg-types = { path = "../dbg-types" }
ssmarshal = "1.0.0"